### PR TITLE
fix: fix deprecation and warnings

### LINKED ISSUE #10: Compile-time warnings
Hello, was just packaging this for the [AUR](https://aur.archlinux.org) when I noticed these issues when running `cargo test`:

```sh
   Compiling licensure v0.1.3 (/build/licensure/src/licensure-0.1.3)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/comments.rs:23:26
   |
23 |     per_line: Option<Box<Comment>>,
   |                          ^^^^^^^ help: use `dyn`: `dyn Comment`
   |
   = note: `#[warn(bare_trait_objects)]` on by default
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>

warning: trait objects without an explicit `dyn` are deprecated
  --> src/comments.rs:97:42
   |
97 | pub fn get_commenter(ftype: &str) -> Box<Comment> {
   |                                          ^^^^^^^ help: use `dyn`: `dyn Comment`
   |
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
   = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>

warning: `licensure` (lib) generated 2 warnings
warning: use of deprecated function `std::env::home_dir`: This function's behavior is unexpected and probably not what you want. Consider using a crate from crates.io instead.
  --> src/main.rs:77:36
   |
77 |     if let Some(mut global) = env::home_dir() {
   |                                    ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: `licensure` (bin "licensure") generated 1 warning
```

Additionally, `Cargo.lock` from the latest release (0.1.3) is out of sync with `Cargo.toml`.

This is a nifty little project! :D

### PR DESCRIPTION
**Pull request by aminya**
- dyn is required
- set_year was unused

Fixes #10

### CODE REVIEW

File: src/template.rs [hunk 1]
```diff
@@ -89,10 +88,10 @@ impl Template {
         self
     }
 
-    pub fn set_year(mut self, year: &str) -> Template {
-        self.context.year = Some(year.to_string());
-        self
-    }
+    // pub fn set_year(mut self, year: &str) -> Template {
```
Comment (chasinglogic) [inline src/template.rs:91]: If it's unused just delete it. That is preferrable to having commented out code.

**Review by chasinglogic — CHANGES_REQUESTED** [review]

File: src/template.rs (hunk 1 above)
Comment (aminya) [reply src/template.rs]: Fixed in 
https://github.com/chasinglogic/licensure/pull/13/commits/5256f585883da0009bbd2a873153272ccb4425e5

**Review by chasinglogic — APPROVED** [review]
